name: CI

on:
  - push
  - pull_request

jobs:
  cabal-build:
    name: Cabal with GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ghc: [ '9.6.4' ]
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: '3.10.3.0' 
      - run: cabal new-build --only-dependencies
      - run: cabal new-build
      # - run: cabal new-test --test-show-details=direct
